// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet_Backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("ReadingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BPM")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyTemperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("ECG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Humidity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomTemperature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spo2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
